### ISSUE TITLE
Outdate documents about ActivityAttributes

### ISSUE THREAD

**Issue by phuchuynhStrong** [istornz/flutter_live_activities#17]
Hello, thanks for such an amazing library. But I encountered a problem when integrating it. Its about missing `public typealias LiveDeliveryData = ContentState` when declaring `LiveActivitiesAppAttributes`. Without that line, no activities would be displayed. I think you should add that line to README in the `LiveActivitiesAppAttributes ` block.

**Comment by istornz** [comment]
Added in ```README.md``` thanks for the suggestion 👍
