### ISSUE TITLE
how to use sharedDefaults for multiple liveactivities

### ISSUE THREAD

**Issue by jolamar** [istornz/flutter_live_activities#19]
when I create multiple live activities the shareddefaults from the initial one get overwritten from the most recent one. Instead of using shared defaults, maybe we can pass in the attributes during createActivity

**Comment by Clon1998** [comment]
I wonder if there is still a discussion about this problem.
I just stumbled across the same issue. When creating multiple LiveActivities. If I create or update different activities to fast, it can happen that the activity uses the wrong data. I tried to add a delay which helped a little but is also really unreliable. In addition, if I update any of the activities via the remote service/APNs the updated activity will use the latest SharedDefault content besides the dynamic data that is provided in the APNs update.
I wonder if we could create the activity and use its `LiveActivitiesAppAttributes.id` to store/access the correct data ib sharedDefaults?

**Comment by istornz** [comment]
Released on v1.9.0, feel free to reopen if any 👍

**Comment by Clon1998** [comment]
> Released on v1.9.0, feel free to reopen if any 👍

No need to reopen this issue. However, I just checked the changelog and they do not include a hint that my PR is actually a breaking one. We might also need to update the readme since it is not valid anymore.
E.g. This Swift Code: `let myVariableFromFlutter = sharedDefault.string(forKey: "myVariableFromFlutter")!` is broken now since the change now forces an prefix for any key usage.

**Comment by istornz** [comment]
> > Released on v1.9.0, feel free to reopen if any 👍
> 
> No need to reopen this issue. However, I just checked the changelog and they do not include a hint that my PR is actually a breaking one. We might also need to update the readme since it is not valid anymore. E.g. This Swift Code: `let myVariableFromFlutter = sharedDefault.string(forKey: "myVariableFromFlutter")!` is broken now since the change now forces an prefix for any key usage.

I added a new section in the [doc](https://github.com/istornz/flutter_live_activities#multiple-notifications-) 👍
