### ISSUE TITLE
No implementation found for method listen on channel live_activities/token_channel

### ISSUE THREAD

**Issue by ErasmoCM** [istornz/flutter_live_activities#27]
Interface to handle `activityUpdateStream` on native was removed in #25 but at the same time recommend to use it.

Which leaves us with the following error
`
MissingPluginException(No implementation found for method listen on channel live_activities/token_channel)
`

**Comment by istornz** [comment]
Hi @ErasmoCM thanks for your issue.

It's now fixed & released as 1.7.1!
