### ISSUE TITLE
Observe push notification token changes

### ISSUE THREAD

**Issue by ggirotto** [istornz/flutter_live_activities#28]
According to Apple docs, it seems that the push token associated with an activity may change during its lifecycle:

> Observe changes to an activity’s push token with [pushTokenUpdates](https://developer.apple.com/documentation/activitykit/activity/pushtokenupdates-swift.property), send an updated push token to your server, and invalidate the old token on your server.

Ref: https://developer.apple.com/documentation/activitykit/updating-and-ending-your-live-activity-with-activitykit-push-notifications

The package exposes a `getPushToken` function that lets us get the latest push token, but shouldn't we have a `Stream` that emits a new event every time the token is updated?

That's more a question to open a discussion than anything else, because it seems that in the iOS side we also don't have a stream to get this token live updates.

**Comment by istornz** [comment]
Hello !

You can listen on the `activityUpdateStream` stream to get the latest pushtoken from Apple 👍 

`getPushToken()` is intended to get a push token manually, but the recommended way is to listen on the stream & update locally you token.

**Comment by jolamar** [comment]
There isn't good (any) documentation on the frequency of the push token updates but in my experience it's not very often. However if/when it does update using a listener on activityUpdateStream should do the trick to get the new token.. here's some sample code:

```
  _liveActivitiesPlugin.activityUpdateStream.listen(listenForLiveActivityEvents);
  listenForLiveActivityEvents(ActivityUpdate activity) {
    LiveActivityState state;
    String pushToken;
    activity.map(
      active: (newActivity) {
        state = LiveActivityState.active;
        pushToken = newActivity.activityToken;
      },
      ended: (_) => state = LiveActivityState.ended,
      unknown: (_) => state = LiveActivityState.unknown,
    );

    switch (state) {
      case LiveActivityState.active:
        updateActivityPushToken(activity.activityId, pushToken);
        break;
      case LiveActivityState.ended:
        revokeLiveActivityPushToken(activity.activityId);
        break;
      default:
        break;
    }
  }
```

**Comment by ggirotto** [comment]
Thanks for the response guys, I haven't realized that I could use the update stream and continuously get the push token.
