### ISSUE TITLE
Make `ActivityUpdate` subclasses public

### ISSUE THREAD

**Issue by ggirotto** [istornz/flutter_live_activities#33]
Is there a reason for all entities that extend from [`ActivityUpdate`](https://github.com/istornz/flutter_live_activities/blob/main/lib/models/activity_update.dart) to not be public?

From my understanding, if we had access to [`_ActiveActivityUpdate`](https://github.com/istornz/flutter_live_activities/blob/8457155795fd99ad6138a42b22890e6f6fb16036/lib/models/activity_update.dart#L40), instead of doing

```dart
_liveActivities.activityUpdateStream.listen((update) async {
      final updatedToken = await _liveActivities.getPushToken(activityId: update.activityId);
      ...
    });
```

We could do just

```dart
_liveActivities.activityUpdateStream.listen((update) async {
      final updatedToken = update is _ActiveActivityUpdate ? update.activityToken : null;
     ...
    });
```

**Comment by istornz** [comment]
It's now published on pub.dev 👍 

Thanks to @arnar-steinthors :)
