### ISSUE TITLE
`areActivitiesEnabled` should be callable from iOS lower than 16.1

### ISSUE THREAD

**Issue by ggirotto** [istornz/flutter_live_activities#35]
The first check from the swift plugin `handle` function is:

https://github.com/istornz/flutter_live_activities/blob/01dfa660fae40c10d533ef2b6c025e6a77a9aa09/ios/Classes/SwiftLiveActivitiesPlugin.swift#L55

This makes impracticable to use `areActivitiesEnabled` function to check if the user is running on iOS lower than 16.1
I'm currently out of time to open a PR, but the change is very easy. Just creating this issue to address the problem and I'll create a PR in the following days if possible.

**Comment by istornz** [comment]
Release 1.7.4 now released & fix this !
