### ISSUE TITLE
I can't launch my application, an error appears : "Type 'ActivityState' has no member 'stale'"

### ISSUE THREAD

**Issue by ambogatyrev** [istornz/flutter_live_activities#36]
The same thing happens with the application from the "example" directory

<img width="914" alt="Без названия" src="https://user-images.githubusercontent.com/79789858/234788487-e44c4ce2-8ddc-46f9-817f-91cd87901858.png">

<details>
  <summary>flutter doctor</summary>
[✓] Flutter (Channel stable, 3.7.11, on macOS 13.2.1 22D68 darwin-arm64, locale ru-KZ)
    • Flutter version 3.7.11 on channel stable at /development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f72efea43c (2 weeks ago), 2023-04-11 11:57:21 -0700
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.77.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (4 available)
    • iPhone 12 Pro Max (mobile)          • B6219DB9-1D8A-4D7F-AD23-B24A898BF26E • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-1 (simulator)
    • iPhone SE (3rd generation) (mobile) • 45187541-7E70-4DEB-BB34-1033614A6B1A • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-1 (simulator)
    • macOS (desktop)                     • macos                                • darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64
    • Chrome (web)                        • chrome                               • web-javascript • Google Chrome 112.0.5615.137

[✓] HTTP Host Availability
    • All required HTTP hosts are available
</details>

**Comment by chaser-young** [comment]
Updating xcode to version 14.3 solved the problem

**Comment by istornz** [comment]
@ambogatyrev Updating Xcode like @chaser-young said fix your problem?

**Comment by ambogatyrev** [comment]
@istornz I launched the Xcode update recently, I will give an answer soon

**Comment by ambogatyrev** [comment]
@chaser-young Thanks!
