### ISSUE TITLE
Debugging the activity widget

### ISSUE THREAD

**Issue by mirkancal** [istornz/flutter_live_activities#5]
Thanks for that amazing package. Example app works great, however when I tried to connect to my app, I wasn't able to run the activities.

I follow the README from scratch 3 times, but no luck. init works, and I can print the id of live activity. When I debug, I can also see that create activity works. But I don't see anything with initial widget code or the package's code(football one), dynamic island is just black from my app.

Is there any additional step to connect live activity widget to app? (I've created the target, add the group ids)

**Comment by mirkancal** [comment]
Hi, I've used 14 pro max simulator. Example app was working on the simulator. As for the waiting init, when I put await on it, it wasn't returning anything at all. So I've used without it, just put 3 seconds delay between init and create. 

Notifications enabled, live activity is also enabled for the app. Putting the app in background, and then clicking on the dynamic island also bring the app back. So it's almost working, but probably couldn't render that live activity widget(swiftUI code). 

Demo widget with L-T or your example, both didn't work. It worked with another package https://pub.dev/packages/flutter_live_activities

So my best guess is, something is not connected to that activity widget or its attributes.

**Comment by istornz** [comment]
I tried to setup from scratch and the tricky stuff is the swift part (which need to be specified in the doc). So be sure to replace the ```ActivityAttributes``` bloc with the followed bloc, it **NEED** to be the name (referenced in the plugin).

So change this bloc:
```
struct MyAppWidgetAttributes: ActivityAttributes {
    public struct ContentState: Codable, Hashable {
        // Dynamic stateful properties about your activity go here!
        var value: Int
    }

    // Fixed non-changing properties about your activity go here!
    var name: String
}
```

To this one (**EXACTLY** the same, do not change anything like renaming method, it will compile but not display live activity):
```
struct LiveActivitiesAppAttributes: ActivityAttributes, Identifiable {
  public struct ContentState: Codable, Hashable { }
  
  var id = UUID()
}
```

And reference it in the ```ActivityConfiguration```

```swift
ActivityConfiguration(for: LiveActivitiesAppAttributes.self)
```

**Comment by mirkancal** [comment]
That makes great sense. I've found your package more developed than the other one(and thanks again). I'll switch back to yours later today and update the issue.

**Comment by jakublebiedzinski** [comment]
How can we manage the state then? Is there any way to have manageable ContentState in the widget?

**Comment by jakublebiedzinski** [comment]
@istornz  Is there any way to use ContentState with dynamic data? I'd like to build sth changeable and dynamic during the lifecycle of the activity.

**Comment by janosdupai** [comment]
Same issue!
Somehow, when I changed the images to another, the live activity not showing.
(if I use the psg and chelsea assets, it works, but if I change them to my own asset, it does not show the live activity on the locked screen). 
--- of course I inserted the images' path into the pubspec.yaml file..

any idea?

**Comment by janosdupai** [comment]
> @janosdupai It it probably because you try to display an image with a too high resolution. You can use the `resizeFactor()` or resize manually your image.
> 
> For more information: https://github.com/istornz/flutter_live_activities#access-flutter-picture-from-native-

Thanks!
