### ISSUE TITLE
Live Activities Extension 'Undefined symbol'

### ISSUE THREAD

**Issue by jakublebiedzinski** [istornz/flutter_live_activities#6]
Hello,

I have already set up the configuration according to your docs, however, when I try to build the iOS app with the extension I get a few errors that suggest there are some issues with Flutter packages. 

![image](https://user-images.githubusercontent.com/102026719/205917069-3ac6a73d-c761-4977-bd98-eae3ec803315.png)

I use MacBook with M1 and the latest version of XCode (Also I try to run the app on the physical device with the latest iOS version).
What should I do? Have you ever seen these messages when building an app with an extension?
Thank you in advance!

**Comment by mirkancal** [comment]
@jakublebiedzinski can you run the example app though?

**Comment by jakublebiedzinski** [comment]
@mirkancal yup, I could build and run example app

**Comment by istornz** [comment]
Hum... this is very strange if the example work & not your app !

Can you check if you done all theses [steps](https://github.com/istornz/live_activities/issues/4#issuecomment-1323423927)  ?
Do you tried to clean your Xcode derived data ?

Thanks !

**Comment by jakublebiedzinski** [comment]
I believe it's connected with the architecture which the app is built with. Has your iOS app been built with x86 architecture? I've noticed that you do not exclude any architectures in the Build Options section in XCode (iOS app).

**Comment by istornz** [comment]
Thanks for your feedback !

Yes this is possible, you can check the example app, there is an [animated countdown timer](https://github.com/istornz/live_activities/blob/b386fcb3e52fe5ff1f4cd757cb5c88b65ce57603/example/ios/extension-example/extension_example.swift#L109) 👍

**Comment by jakublebiedzinski** [comment]
I saw that but you use a special function to count down, however, I'd like to count how much time elapsed since a date I provide with shared values and it is not possible with the timerInterval and countDown parameters.

**Comment by mirkancal** [comment]
@jakublebiedzinski I think it's also possible to use updateActivity from dart code

**Comment by jakublebiedzinski** [comment]
Here I have some logs when linking my extension:

![image](https://user-images.githubusercontent.com/102026719/206436635-c4430bfe-c033-49b6-abdb-55174ae2fb7b.png)

**Comment by istornz** [comment]
> Here I have some logs when linking my extension:
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/102026719/206436635-c4430bfe-c033-49b6-abdb-55174ae2fb7b.png)
> 
> 

Are you sure it's related to live_activities ?

**Comment by jakublebiedzinski** [comment]
I had to add the Run script in the extension target so it could find the Flutter framework. The script is the the same as in Runner target.
