### ISSUE TITLE
Multiple notifications support broke the library usage for single notifications

### ISSUE THREAD

**Issue by ggirotto** [istornz/flutter_live_activities#69]
The new multiple notifications addition (https://pub.dev/packages/live_activities#multiple-notifications-) broke the app for single notification usage. The step of getting the notification from user defaults now fail if the key prefix implementation is not added.

**Comment by Clon1998** [comment]
Tl; DR;

To migrate from `1.8.x` -> `1.9.x`:

1. Add the new extension to the end of your file or as a new file you want to import:
```swift
extension LiveActivitiesAppAttributes {
  func prefixedKey(_ key: String) -> String {
    return "\(id)_\(key)"
  }
}
```

2. Replace all access to the `sharedDefault` with the prefixed version:

```swift
ActivityConfiguration(for: LiveActivitiesAppAttributes.self) { context in
   ...
  // old
  let matchName = sharedDefault.string(forKey: "matchName")!

  // new
  let matchName = sharedDefault.string(forKey: context.attributes.prefixedKey("matchName"))!
   ...
```

**Comment by istornz** [comment]
Hi @ggirotto !
As @Clon1998 said, now you need to add a prefix even for single notification. I updated README.md file & put the [1.9.0 release](https://github.com/istornz/flutter_live_activities/blob/main/CHANGELOG.md) as Breaking Changes.

If we found an another solution I will remove the dependence of prefix for single based notification 👍

**Comment by ggirotto** [comment]
Hey guys,

Sorry, that was my bad. I didn't pay attention to README and CHANGELOG before creating this ticket. The steps are well described there. Thanks for the answers!
