### ISSUE TITLE
Activity update: EndedActivityUpdate(activityId: "Some ID") as soon as i create an activity i get this log for some reason using the default app sample widget

### ISSUE THREAD

**Issue by OmerTrainer** [istornz/flutter_live_activities#72]

**Comment by OmerTrainer** [comment]
problem was solved make sure to make app group id capability on all modes

**Comment by adham-ashraf77** [comment]
@OmerTrainer  I got the same error any help?

**Comment by OmerTrainer** [comment]
just make sure the main runner app is configured correctly with the app-group id capability

> @OmerTrainer I got the same error any help?

**Comment by adham-ashraf77** [comment]
> just make sure the main runner app is configured correctly with the app-group id capability
> 
> > @OmerTrainer I got the same error any help?

I make sure that are the same group id what else should I see 
I want to show the default view only now

**Comment by adham-ashraf77** [comment]
![WhatsApp Image 2024-06-12 at 10 21 33_f3a3fe24](https://github.com/istornz/flutter_live_activities/assets/55947445/57d8ebe6-0efb-4f47-ad3b-3d6e174178e5)
![WhatsApp Image 2024-06-12 at 10 21 33_d20b61d1](https://github.com/istornz/flutter_live_activities/assets/55947445/cf9d3adf-ba24-411a-a6c6-c11f8291fc19)

**Comment by OmerTrainer** [comment]
> ![WhatsApp Image 2024-06-12 at 10 21 33_f3a3fe24](https://private-user-images.githubusercontent.com/55947445/338862628-57d8ebe6-0efb-4f47-ad3b-3d6e174178e5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNzc4NTksIm5iZiI6MTcxODE3NzU1OSwicGF0aCI6Ii81NTk0NzQ0NS8zMzg4NjI2MjgtNTdkOGViZTYtMGVmYi00ZjQ3LWFkM2ItM2Q2ZTE3NDE3OGU1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDA3MzIzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1NTE1MTU3Zjg4NjA4N2I2NDY5YTdjZmQ2YmEzODZjMGI5ZjY2YmEwODQyMGZjM2JlNGQ5ODhkY2I3MjdiM2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.63OcRngC5x4SPI8IAgHs3ddjhVR3LwP7BiYpbegZsL0) ![WhatsApp Image 2024-06-12 at 10 21 33_d20b61d1](https://private-user-images.githubusercontent.com/55947445/338862656-cf9d3adf-ba24-411a-a6c6-c11f8291fc19.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNzc4NTksIm5iZiI6MTcxODE3NzU1OSwicGF0aCI6Ii81NTk0NzQ0NS8zMzg4NjI2NTYtY2Y5ZDNhZGYtYmEyNC00MTFhLWE2YzYtYzExZjgyOTFmYzE5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDA3MzIzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1OTc3MzU1ZWZiNzhhNDczZmRkNGUzYWUzYWEyYWNhMzgxZmRjZjA1M2U5ZWI1MzU1MWZlYjFmOGM5MzcwYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I698rOcpZBg8Qn1BK8NNyiI2CmmGQxCLHtudrguYfR4)

the problem i had is that i wrongfully added App Groups  capability not to my main app runner i can't tell if you did that by the screenshot that you provided but if you configured it right then the problem should be somewhere else

**Comment by adham-ashraf77** [comment]
@OmerTrainer  can we get a quick meeting if you have a time ?

**Comment by OmerTrainer** [comment]
> problem was solved make sure to make app group id capability on all modes

yes, but i would prefer to help you in this thread so everyone that encounters this can enjoy the solution.

**Comment by OmerTrainer** [comment]
![Screenshot 2024-06-12 at 10 43 12](https://github.com/istornz/flutter_live_activities/assets/92077528/3e70303a-20ac-42ae-93e0-12724f336b47)
make sure "All" is selected when you add the capability both on the main runner app and the live activity extenstion

**Comment by adham-ashraf77** [comment]
> > problem was solved make sure to make app group id capability on all modes
> 
> yes, but i would prefer to help you in this thread so everyone that encounters this can enjoy the solution.

yes I will make sure I write the solution after solve it 
can you connect me at adhamashraf51@gmail.com

**Comment by adham-ashraf77** [comment]
flutter: F0821F95-CCAD-43F2-A073-329811474699
flutter: Activity update: EndedActivityUpdate(activityId: F0821F95-CCAD-43F2-A073-329811474699) 
   final activityId = await _liveActivitiesPlugin .createActivity({});
@OmerTrainer

**Comment by OmerTrainer** [comment]
> dhamashraf51@gmail.com

why are you passing an empty map "{}" as a paremeter when creating an activity ? make sure first you can run the sample project see if it works correctly

**Comment by adham-ashraf77** [comment]
> > [dhamashraf51@gmail.com](mailto:dhamashraf51@gmail.com)
> 
> why are you passing an empty map "{}" as a paremeter when creating an activity ? make sure first you can run the sample project see if it works correctly

I want to show only the default view

**Comment by OmerTrainer** [comment]
> > > [dhamashraf51@gmail.com](mailto:dhamashraf51@gmail.com)
> > 
> > 
> > why are you passing an empty map "{}" as a paremeter when creating an activity ? make sure first you can run the sample project see if it works correctly
> 
> I want to show only the default view

The "Default" view also requires some params.... Look at the "Content-State" in the liveactivity extension to see what params you need to pass

**Comment by adham-ashraf77** [comment]
> > > > [dhamashraf51@gmail.com](mailto:dhamashraf51@gmail.com)
> > > 
> > > 
> > > why are you passing an empty map "{}" as a paremeter when creating an activity ? make sure first you can run the sample project see if it works correctly
> > 
> > 
> > I want to show only the default view
> 
> The "Default" view also requires some params.... Look at the "Content-State" in the liveactivity extension to see what params you need to pass

![WhatsApp Image 2024-06-12 at 11 20 09_61945320](https://github.com/istornz/flutter_live_activities/assets/55947445/94575c1e-4891-424d-9220-698886e28dff)

this is my liveactivity

**Comment by OmerTrainer** [comment]
> > > > > [dhamashraf51@gmail.com](mailto:dhamashraf51@gmail.com)
> > > > 
> > > > 
> > > > why are you passing an empty map "{}" as a paremeter when creating an activity ? make sure first you can run the sample project see if it works correctly
> > > 
> > > 
> > > I want to show only the default view
> > 
> > 
> > The "Default" view also requires some params.... Look at the "Content-State" in the liveactivity extension to see what params you need to pass
> 
> ![WhatsApp Image 2024-06-12 at 11 20 09_61945320](https://private-user-images.githubusercontent.com/55947445/338881320-94575c1e-4891-424d-9220-698886e28dff.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxODEwMzksIm5iZiI6MTcxODE4MDczOSwicGF0aCI6Ii81NTk0NzQ0NS8zMzg4ODEzMjAtOTQ1NzVjMWUtNDg5MS00MjRkLTkyMjAtNjk4ODg2ZTI4ZGZmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDA4MjUzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2MmIyZjcwNjAwZDNlZjEwMzYxMGIzNDlhNzE3MmFiMDVlM2JhYjExMDExYWYxZDJjNGE3OWMzZDNhMDY4MzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dX5RYGpqo_92YKumPx2yB7-9SrtxsLHin6yQGmd4rIM)
> 
> this is my live activity @OmerTrainer

you need to provide "emoji" and "name" or just delete all the fields and make an hard coded view that doesn't relay on the params

**Comment by adham-ashraf77** [comment]
> > > > > > [dhamashraf51@gmail.com](mailto:dhamashraf51@gmail.com)
> > > > > 
> > > > > 
> > > > > why are you passing an empty map "{}" as a paremeter when creating an activity ? make sure first you can run the sample project see if it works correctly
> > > > 
> > > > 
> > > > I want to show only the default view
> > > 
> > > 
> > > The "Default" view also requires some params.... Look at the "Content-State" in the liveactivity extension to see what params you need to pass
> > 
> > 
> > ![WhatsApp Image 2024-06-12 at 11 20 09_61945320](https://private-user-images.githubusercontent.com/55947445/338881320-94575c1e-4891-424d-9220-698886e28dff.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxODEwMzksIm5iZiI6MTcxODE4MDczOSwicGF0aCI6Ii81NTk0NzQ0NS8zMzg4ODEzMjAtOTQ1NzVjMWUtNDg5MS00MjRkLTkyMjAtNjk4ODg2ZTI4ZGZmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDA4MjUzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2MmIyZjcwNjAwZDNlZjEwMzYxMGIzNDlhNzE3MmFiMDVlM2JhYjExMDExYWYxZDJjNGE3OWMzZDNhMDY4MzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dX5RYGpqo_92YKumPx2yB7-9SrtxsLHin6yQGmd4rIM)
> > this is my live activity @OmerTrainer
> 
> you need to provide "emoji" and "name" or just delete all the fields and make an hard coded view that doesn't relay on the params

how to provide them please?

**Comment by OmerTrainer** [comment]
> > > > > > > [dhamashraf51@gmail.com](mailto:dhamashraf51@gmail.com)
> > > > > > 
> > > > > > 
> > > > > > why are you passing an empty map "{}" as a paremeter when creating an activity ? make sure first you can run the sample project see if it works correctly
> > > > > 
> > > > > 
> > > > > I want to show only the default view
> > > > 
> > > > 
> > > > The "Default" view also requires some params.... Look at the "Content-State" in the liveactivity extension to see what params you need to pass
> > > 
> > > 
> > > ![WhatsApp Image 2024-06-12 at 11 20 09_61945320](https://private-user-images.githubusercontent.com/55947445/338881320-94575c1e-4891-424d-9220-698886e28dff.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxODEwMzksIm5iZiI6MTcxODE4MDczOSwicGF0aCI6Ii81NTk0NzQ0NS8zMzg4ODEzMjAtOTQ1NzVjMWUtNDg5MS00MjRkLTkyMjAtNjk4ODg2ZTI4ZGZmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDA4MjUzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2MmIyZjcwNjAwZDNlZjEwMzYxMGIzNDlhNzE3MmFiMDVlM2JhYjExMDExYWYxZDJjNGE3OWMzZDNhMDY4MzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dX5RYGpqo_92YKumPx2yB7-9SrtxsLHin6yQGmd4rIM)
> > > this is my live activity @OmerTrainer
> > 
> > 
> > you need to provide "emoji" and "name" or just delete all the fields and make an hard coded view that doesn't relay on the params
> 
> how to provide them please?

await _liveActivitiesPlugin .createActivity({"emoji": "sample","name": "sampleName"});

**Comment by adham-ashraf77** [comment]
![WhatsApp Image 2024-06-12 at 11 40 20_dd67b512](https://github.com/istornz/flutter_live_activities/assets/55947445/7296e244-f69e-44c8-924a-92119d670fa7)
same result no changes

**Comment by OmerTrainer** [comment]
> ![WhatsApp Image 2024-06-12 at 11 40 20_dd67b512](https://private-user-images.githubusercontent.com/55947445/338888110-7296e244-f69e-44c8-924a-92119d670fa7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxODE5NTcsIm5iZiI6MTcxODE4MTY1NywicGF0aCI6Ii81NTk0NzQ0NS8zMzg4ODgxMTAtNzI5NmUyNDQtZjY5ZS00NGM4LTkyNGEtOTIxMTlkNjcwZmE3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDA4NDA1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhMjBhNzg3NDRiMTNmMTZiNTM1OGRmMDMxZDA2Nzg0YTYwYTk5MDg5MmEwYmIwMDY3OTg5NTliNWQ4MzkyZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.K0Rgx3i7CPDPtpXkeAmgAG5xIUcIuRIHpzYsW2ZRtlc) same result no changes @OmerTrainer

you might consider researching a bit more on how it works before trying to implement it. first try to build the sample project that is provided with the package

**Comment by adham-ashraf77** [comment]
> > ![WhatsApp Image 2024-06-12 at 11 40 20_dd67b512](https://private-user-images.githubusercontent.com/55947445/338888110-7296e244-f69e-44c8-924a-92119d670fa7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxODE5NTcsIm5iZiI6MTcxODE4MTY1NywicGF0aCI6Ii81NTk0NzQ0NS8zMzg4ODgxMTAtNzI5NmUyNDQtZjY5ZS00NGM4LTkyNGEtOTIxMTlkNjcwZmE3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDA4NDA1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhMjBhNzg3NDRiMTNmMTZiNTM1OGRmMDMxZDA2Nzg0YTYwYTk5MDg5MmEwYmIwMDY3OTg5NTliNWQ4MzkyZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.K0Rgx3i7CPDPtpXkeAmgAG5xIUcIuRIHpzYsW2ZRtlc) same result no changes @OmerTrainer
> 
> you might consider researching a bit more on how it works before trying to implement it. first try to build the sample project that is provided with the package

I really tried many times don't know what is the real issue if you have some time please connect me at adhamashraf51@gmail.com

**Comment by OmerTrainer** [comment]
> > > ![WhatsApp Image 2024-06-12 at 11 40 20_dd67b512](https://private-user-images.githubusercontent.com/55947445/338888110-7296e244-f69e-44c8-924a-92119d670fa7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxODE5NTcsIm5iZiI6MTcxODE4MTY1NywicGF0aCI6Ii81NTk0NzQ0NS8zMzg4ODgxMTAtNzI5NmUyNDQtZjY5ZS00NGM4LTkyNGEtOTIxMTlkNjcwZmE3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDA4NDA1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhMjBhNzg3NDRiMTNmMTZiNTM1OGRmMDMxZDA2Nzg0YTYwYTk5MDg5MmEwYmIwMDY3OTg5NTliNWQ4MzkyZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.K0Rgx3i7CPDPtpXkeAmgAG5xIUcIuRIHpzYsW2ZRtlc) same result no changes @OmerTrainer
> > 
> > 
> > you might consider researching a bit more on how it works before trying to implement it. first try to build the sample project that is provided with the package
> 
> I really tried many times don't know what is the real issue if you have some time please connect me at [adhamashraf51@gmail.com](mailto:adhamashraf51@gmail.com)

you can reach me out at omertrainer3402@gmail.com i will try to do my best to help :)

**Comment by adham-ashraf77** [comment]
[ERROR:flutter/shell/common/shell.cc(1055)] The 'live_activities/activity_status' channel sent a message from native to Flutter on a non-platform thread. Platform channel messages must be sent on the platform thread. Failure to do so may result in data loss or crashes, and must be fixed in the plugin or application code creating that channel.
See https://docs.flutter.dev/platform-integration/platform-channels#channels-and-platform-threading for more information.

@OmerTrainer  new error
