### ISSUE TITLE
Is it possible to use SVG images?

### ISSUE THREAD

**Issue by lazarohcm** [istornz/flutter_live_activities#74]
Sorry if this is not the right place, but I've looked everywhere and couldn't find an answer.

As the title says, I'm wondering if I can use an SVG image and display it in the live activity?
I currently have an implementation that works fine with .png, but I'm not able to make it display .svg?

This is how the code looks like:

```swift
if let venueImageAssest = UIImage(contentsOfFile: venueImage)
{
    Image(uiImage: venueImageAssest)
        .resizable()
}
```

`venueImage` is currently an `LiveActivityImageFromUrl`

Any help is much appreciated, thanks!

**Comment by istornz** [comment]
Hello @lazarohcm, It seems you need to add an external Swift library to display it 👍 

https://stackoverflow.com/a/74203993/5078902

**Comment by fabiototh** [comment]
1. Add the package: SVGKit -> https://github.com/SVGKit/SVGKit
2. import SVGKit
3. if let uiYourLogo = SVGKImage(contentsOfFile: yourLogo) 
4. inside the brackets  Image(uiImage: uiActivityLogo.uiImage)
