### ISSUE TITLE
Not working in test flight

### ISSUE THREAD

**Issue by Vagif07** [istornz/flutter_live_activities#83]
I would highly appreciate any ideas. I was able to successfully integrate this great package and everything seemed to work great on my physical device, while it was connected to the computer that was running the flutter application. However when launching the same application on the test flight (on the same device), the live activity is not created at all. What can be the reason? 

Edit:
I figured that I can test using flutter run —release and see how the app behaves then. I will update in case I find the solution

**Comment by istornz** [comment]
Hello @Vagif07, do you have found any solutions?

**Comment by istornz** [comment]
I close the issue, feel free to reopen if the issue persist 👍
