### ISSUE TITLE
areActivitiesEnabled crashes silicon mac

### ISSUE THREAD

**Issue by jin-motemote** [istornz/flutter_live_activities#84]
Tested on Flutter 3.19.3

`Parent Process:      launchd [1]
Coalition:           com.motemote.allcl [11739]

Date/Time:           2024-06-04 18:14:47.4075 +0900
Launch Time:         2024-06-04 18:14:31.7632 +0900
OS Version:          macOS 14.1 (23B74)
Release Type:        User
Report Version:      104

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Codes: 0x0000000000000001, 0x0000000000000000
VM Region Info: 0 is not in any region.  Bytes before following region: 4366155776
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                      1043e4000-1043ec000    [   32K] r-x/r-x SM=COW  ...er.app/Runner
Termination Reason: SIGNAL 11 Segmentation fault: 11
Terminating Process: exc handler [44964]

Triggered by Thread:  0

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   ???                           	               0x0 ???
1   live_activities               	       0x105e6a2f0 @objc SwiftLiveActivitiesPlugin.handle(_:result:) + 84
2   Flutter                       	       0x107354a8c 0x106d94000 + 6032012
3   Flutter                       	       0x106dd7d0c 0x106d94000 + 277772
4   libdispatch.dylib             	       0x18e87dcb8 _dispatch_call_block_and_release + 32
5   libdispatch.dylib             	       0x18e87f910 _dispatch_client_callout + 20
6   libdispatch.dylib             	       0x18e88dfa8 _dispatch_main_queue_drain + 984
7   libdispatch.dylib             	       0x18e88dbc0 _dispatch_main_queue_callback_4CF + 44
8   CoreFoundation                	       0x18eb4b15c __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
9   CoreFoundation                	       0x18eb08a80 __CFRunLoopRun + 1996
10  CoreFoundation                	       0x18eb07c5c CFRunLoopRunSpecific + 608
11  HIToolbox                     	       0x199081448 RunCurrentEventLoopInMode + 292
12  HIToolbox                     	       0x199081284 ReceiveNextEventCommon + 648
13  HIToolbox                     	       0x199080fdc _BlockUntilNextEventMatchingListInModeWithFilter + 76
14  AppKit                        	       0x1922e2c54 _DPSNextEvent + 660
15  AppKit                        	       0x192ab8ebc -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 716
16  AppKit                        	       0x1922d6100 -[NSApplication run] + 476
17  AppKit                        	       0x1922ad3cc NSApplicationMain + 880
18  AppKit                        	       0x192500240 _NSApplicationMainWithInfoDictionary + 24
19  UIKitMacHelper                	       0x1a76b4d8c UINSApplicationMain + 972
20  UIKitCore                     	       0x1bd04493c UIApplicationMain + 148
21  Runner                        	       0x1043ed960 0x1043e4000 + 39264
22  dyld                          	       0x18e6b10e0 start + 2360

**Comment by istornz** [comment]
Fixed on 1.9.3 version, thanks 👍
